Write-Host "============================================================"
Write-Host "Name:      Vulkan"
Write-Host "Email:     whatever@gmail.com"
Write-Host "Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "Hostname:  $env:COMPUTERNAME"
Write-Host "IP:        $((Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.IPAddress -notlike '169.*' -and $_.IPAddress -ne '127.0.0.1'} | Select-Object -First 1).IPAddress)"
Write-Host "============================================================"